get http://localhost:8080/getproduct/3

###
get http://localhost:8080/getproducts

###
post http://localhost:8080/addproduct
Content-Type: application/json

{
    "name": "ted",
    "price": "807",
    "location": "hospital"
}

###
get http://localhost:8080/getPage
Content-Type: text/html